-- CreateEnum
CREATE TYPE "OTP_TYPE" AS ENUM ('LOGIN', 'ACCESS_TOKEN', 'SIGN_UP', 'FORGOT_PASSWORD');

-- CreateTable
CREATE TABLE "Otp" (
    "id" TEXT NOT NULL,
    "value" TEXT NOT NULL DEFAULT '',
    "type" "OTP_TYPE" NOT NULL DEFAULT 'SIGN_UP',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiredAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "user_id" TEXT,

    CONSTRAINT "Otp_pkey" PRIMARY KEY ("id")
);
